title = "Visáért alapítvány"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Rólunk"
    url = "/about"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Beszámolók"
    url = "/posts"
    weight = 20