title = "Visáért alapítvány"

[menu]
  [[menu.main]]
    identifier = "village"
    name = "A faluról"
    url = "/village"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Beszámolók"
    url = "/posts"
    weight = 20