title = "Visáért Alapítvány"
theme = ["hugo-shortcode-gallery"]

[menu]
  [[menu.main]]
    identifier = "village"
    name = "A faluról"
    url = "/village"
    weight = 10

  [[menu.main]]
    identifier = "gallery"
    name = "Galéria"
    url = "/gallery"
    weight = 20

  [[menu.main]]
    identifier = "posts"
    name = "Beszámolók"
    url = "/posts"
    weight = 30